#!/usr/bin/env python3
"""Collect Gate 16 arrival states with the full production navigation stack.

Run inside the development container with the study directory mounted at ``/res``::

    python3 scripts/run_pitfail.py --experiment A --seeds 3 --video-seeds 0

Experiment A runs the router in shadow: it observes and changes state, but the follower's
Twist reaches the shipped locomotion policy unchanged. No climb policy takes joint ownership.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import json
import math
import os
import queue
import signal
import subprocess
import sys
import time
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
COURSE = REPO / "src/s10_bringup/config/course.yaml"
NAV = REPO / "src/s10_bringup/config/nav.yaml"
STRATEGY = REPO / "src/s10_bringup/config/strategy.yaml"
INSTALL = Path(os.environ.get("S10_INSTALL_BASE", REPO / "install"))
POLICY_WARMUP = 2.0
SHUTDOWN_GRACE = 8.0


def _run_id(args, obstacle: dict, seed: int) -> str:
    radius_tag = f"r{int(round(args.advance_radius * 100)):03d}"
    extra = f"_{args.tag}" if args.tag else ""
    return f"{args.experiment}_{obstacle['id']}_{radius_tag}{extra}_seed{seed:03d}"


def _load_obstacle(path: Path, obstacle_id: str) -> dict:
    data = yaml.safe_load(path.read_text())
    found = [item for item in data.get("obstacles", []) if item.get("id") == obstacle_id]
    if len(found) != 1:
        raise RuntimeError(f"expected one obstacle {obstacle_id!r}, found {len(found)}")
    return found[0]


def _write_configs(
    root: Path,
    obstacle: dict,
    advance_radius: float,
    experiment: str,
    approach_speed_scale: float,
) -> dict[str, Path]:
    generated = root / "config/generated"
    generated.mkdir(parents=True, exist_ok=True)
    waypoints = yaml.safe_load(COURSE.read_text())["waypoints"]
    start = int(obstacle["approach_from"])
    end = int(obstacle["segment"][1])

    course_path = generated / f"course_{obstacle['id']}.yaml"
    course_path.write_text(
        "# Generated by scripts/run_pitfail.py; source course.yaml is unchanged.\n"
        + yaml.safe_dump(
            {
                "metadata": {
                    "source": str(COURSE),
                    "segment": [start, end],
                    "obstacle": obstacle["id"],
                },
                "waypoints": waypoints[start : end + 1],
            },
            sort_keys=False,
        )
    )

    nav = yaml.safe_load(NAV.read_text())
    nav["waypoint_follower"]["ros__parameters"]["advance_radius"] = advance_radius
    nav_path = generated / f"nav_advance_{advance_radius:.2f}.yaml"
    nav_path.write_text(yaml.safe_dump(nav, sort_keys=False))

    strategy = yaml.safe_load(STRATEGY.read_text())
    params = strategy["strategy_router"]["ros__parameters"]
    params["climb_enabled"] = True
    params["measurement_only"] = experiment == "B"
    params["approach_speed_scale"] = approach_speed_scale
    params["climb_policy"] = "mock"
    params["climb_segment"] = [int(value) for value in obstacle["segment"]]
    params["climb_obstacle_x"] = float(obstacle["edge_center"][0])
    params["climb_edge_center"] = [float(value) for value in obstacle["edge_center"][:2]]
    params["climb_normal"] = [float(value) for value in obstacle["normal"]]
    params["climb_tangent"] = [float(value) for value in obstacle["tangent"]]
    params["advance_radius"] = advance_radius
    strategy_path = generated / f"strategy_{obstacle['id']}.yaml"
    strategy_path.write_text(yaml.safe_dump(strategy, sort_keys=False))
    return {"course": course_path, "nav": nav_path, "strategy": strategy_path}


def _spawn_environment(obstacle: dict, course_path: Path, seed: int) -> dict[str, str]:
    waypoints = yaml.safe_load(course_path.read_text())["waypoints"]
    here, nxt = waypoints[0]["position"], waypoints[1]["position"]
    yaw = math.atan2(nxt[1] - here[1], nxt[0] - here[0])
    return {
        "S10_SPAWN_XY": f"{here[0]},{here[1]}",
        "S10_SPAWN_Z": str(here[2]),
        "S10_SPAWN_YAW": str(yaw),
        "S10_SPAWN_SEED": str(seed),
        "S10_SPAWN_INDEX": str(obstacle["approach_from"]),
        # Natural arrival varies approach pose. Joint jitter instead tests stand-up and
        # can make MuJoCo unstable before navigation starts, which is another experiment.
        "S10_SPAWN_JOINT_SIGMA": "0",
        "S10_USE_VIEWER": "0",
    }


def _terminate(process: subprocess.Popen | None) -> None:
    if process is None or process.poll() is not None:
        return
    process.send_signal(signal.SIGINT)
    try:
        process.wait(SHUTDOWN_GRACE)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait()


def _invalidate_stale_startup(result: dict) -> bool:
    """Reject infrastructure startup failures before they enter capability statistics."""
    transitions = result.get("transitions", [])
    if not any("sensors stale" in str(item).lower() for item in transitions):
        return False
    result["valid"] = False
    result["outcome"] = "invalid startup: sensors stale"
    result["failure_class"] = "sensor_stale"
    return True


def _read_result(path: Path) -> dict:
    result = json.loads(path.read_text())
    if _invalidate_stale_startup(result):
        path.write_text(json.dumps(result, indent=2) + "\n")
    return result


def _run_once(args, obstacle: dict, paths: dict[str, Path], seed: int, ros_domain_id: int) -> dict:
    run_id = _run_id(args, obstacle, seed)
    run_dir = args.root / "raw" / obstacle["id"] / run_id
    env = dict(os.environ)
    env.update(_spawn_environment(obstacle, paths["course"], seed))
    # Concurrent ROS graphs must not discover one another. Sharing a domain here can route a
    # follower from one seed into another seed's policy and silently invalidate both trials.
    env["ROS_DOMAIN_ID"] = str(ros_domain_id)
    if seed in args.video_seeds:
        env["S10_SEGMENT_VIDEO"] = str(run_dir / "frames")
        env["S10_SEGMENT_VIDEO_HZ"] = str(args.video_hz)

    command = [
        "ros2",
        "launch",
        "s10_bringup",
        "pitfail.launch.py",
        f"course_file:={paths['course']}",
        f"nav_params:={paths['nav']}",
        f"router_params:={paths['strategy']}",
        f"out_root:={args.root}",
        f"obstacles_file:={args.obstacles}",
        f"run_id:={run_id}",
        f"obstacle_id:={obstacle['id']}",
        f"experiment:={args.experiment}",
        f"seed:={seed}",
        f"max_time:={args.max_time}",
        f"reach_radius:={args.advance_radius}",
        f"router_shadow:={'true' if args.experiment == 'A' else 'false'}",
        "strategy_router:=true",
    ]
    if args.dry_run:
        print(" ".join(command))
        return {"run_id": run_id, "dry_run": True, "ros_domain_id": ros_domain_id}

    run_dir.mkdir(parents=True, exist_ok=True)
    policy = stack = None
    with (run_dir / "run.log").open("w") as log:
        try:
            policy = subprocess.Popen(
                ["ros2", "run", "s10_sdk_deploy", "rl_deploy"],
                env=env,
                stdout=log,
                stderr=log,
            )
            time.sleep(POLICY_WARMUP)
            stack = subprocess.Popen(command, env=env, stdout=log, stderr=log)
            deadline = time.monotonic() + args.max_time + 60.0
            while stack.poll() is None and time.monotonic() < deadline:
                time.sleep(0.5)
        finally:
            _terminate(stack)
            _terminate(policy)

    result_path = run_dir / "result.json"
    if result_path.is_file():
        return _read_result(result_path)
    result = {
        "run_id": run_id,
        "obstacle_id": obstacle["id"],
        "experiment": args.experiment,
        "seed": seed,
        "valid": False,
        "outcome": "stack exited without result.json",
        "failure_class": "harness_failure",
        "ros_domain_id": ros_domain_id,
    }
    result_path.write_text(json.dumps(result, indent=2) + "\n")
    return result


def _write_manifest(args, obstacle: dict, results: list[dict]) -> None:
    path = args.root / "manifest.json"
    existing = json.loads(path.read_text()) if path.is_file() else {"runs": []}
    by_id = {item["run_id"]: item for item in existing.get("runs", [])}
    observed = [
        "t",
        "x",
        "y",
        "z",
        "qw",
        "qx",
        "qy",
        "qz",
        "yaw_deg",
        "pitch_deg",
        "roll_deg",
        "tilt_deg",
        "cmd_forward",
        "cmd_lateral",
        "cmd_yaw",
        "vx",
        "vy",
        "vz",
        "yaw_rate",
        "obstacle_distance",
        "lateral_error",
        "heading_error",
        "forward_speed",
        "lateral_speed",
        "front_axle_distance",
        "scan_ahead",
    ]
    for result in results:
        by_id[result["run_id"]] = {
            "run_id": result["run_id"],
            "obstacle_id": obstacle["id"],
            "experiment": args.experiment,
            "seed": result.get("seed"),
            "advance_radius_m": args.advance_radius,
            "spawn_position_sigma_m": 0.05,
            "spawn_yaw_sigma_deg": 4.0,
            "spawn_joint_sigma": 0.0,
            "approach_speed_scale": args.approach_speed_scale,
            "ros_domain_id": result.get("ros_domain_id"),
            "observed_fields": observed,
        }
    existing["runs"] = [by_id[key] for key in sorted(by_id)]
    existing["advance_radii_m"] = sorted(
        {item.get("advance_radius_m") for item in existing["runs"]}
    )
    existing["note"] = "Experiment A uses router shadow; /JOINTS_CMD remains official."
    path.write_text(json.dumps(existing, indent=2) + "\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", type=Path, default=Path("/res/pitfail"))
    parser.add_argument("--obstacles", type=Path, default=None)
    parser.add_argument("--obstacle", default="gate16")
    parser.add_argument("--experiment", choices=("A", "B"), default="A")
    parser.add_argument("--seeds", type=int, default=3)
    parser.add_argument("--seed-from", type=int, default=0)
    parser.add_argument("--max-time", type=float, default=120.0)
    parser.add_argument("--advance-radius", type=float, default=0.18)
    parser.add_argument("--approach-speed-scale", type=float, default=0.5)
    parser.add_argument("--tag", default="")
    parser.add_argument("--video-seeds", type=int, nargs="*", default=[])
    parser.add_argument("--video-hz", type=float, default=10.0)
    parser.add_argument(
        "--workers",
        type=int,
        default=1,
        help="Concurrent isolated ROS graphs. Each worker receives its own ROS domain.",
    )
    parser.add_argument(
        "--ros-domain-base",
        type=int,
        default=31,
        help="First ROS_DOMAIN_ID reserved for this batch.",
    )
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Keep completed result.json files and run only missing seeds.",
    )
    args = parser.parse_args(argv)
    args.root = args.root.resolve()
    args.obstacles = (args.obstacles or args.root / "config/obstacles.yaml").resolve()
    args.video_seeds = set(args.video_seeds)
    if args.tag and not args.tag.replace("-", "").replace("_", "").isalnum():
        parser.error("--tag may contain only letters, digits, '-' and '_'")
    if args.workers < 1:
        parser.error("--workers must be at least 1")
    if args.workers > args.seeds:
        args.workers = args.seeds
    if not 0 <= args.ros_domain_base <= 232:
        parser.error("--ros-domain-base must be between 0 and 232")
    if args.ros_domain_base + args.workers - 1 > 232:
        parser.error("worker ROS domain range exceeds 232")

    if not args.dry_run and not (INSTALL / "setup.bash").is_file():
        print(f"error: workspace not built at {INSTALL}", file=sys.stderr)
        return 2
    obstacle = _load_obstacle(args.obstacles, args.obstacle)
    paths = _write_configs(
        args.root,
        obstacle,
        args.advance_radius,
        args.experiment,
        args.approach_speed_scale,
    )
    results = []
    seeds = list(range(args.seed_from, args.seed_from + args.seeds))
    pending_seeds = []
    for seed in seeds:
        result_path = (
            args.root / "raw" / obstacle["id"] / _run_id(args, obstacle, seed) / "result.json"
        )
        if args.resume and result_path.is_file():
            result = _read_result(result_path)
            if result.get("valid"):
                results.append(result)
                print(f"{result['run_id']}: skipped (existing valid result.json)", flush=True)
            else:
                pending_seeds.append(seed)
                print(
                    f"{result['run_id']}: retrying invalid result "
                    f"({result.get('failure_class', 'unknown')})",
                    flush=True,
                )
        else:
            pending_seeds.append(seed)
    if not pending_seeds:
        if not args.dry_run:
            _write_manifest(args, obstacle, results)
        return 0 if all(result.get("valid") for result in results) else 1

    active_workers = min(args.workers, len(pending_seeds))
    if active_workers > 1:
        print(
            "warning: parallel MuJoCo graphs can cause stale sensors under CPU pressure; "
            "validate timing before accepting the batch",
            file=sys.stderr,
            flush=True,
        )
    domains: queue.Queue[int] = queue.Queue()
    for offset in range(active_workers):
        domains.put(args.ros_domain_base + offset)

    def run_isolated(seed: int) -> dict:
        domain = domains.get()
        try:
            result = _run_once(args, obstacle, paths, seed, domain)
            result.setdefault("ros_domain_id", domain)
            return result
        finally:
            domains.put(domain)

    with concurrent.futures.ThreadPoolExecutor(max_workers=active_workers) as executor:
        pending = {executor.submit(run_isolated, seed): seed for seed in pending_seeds}
        for future in concurrent.futures.as_completed(pending):
            seed = pending[future]
            try:
                result = future.result()
            except Exception as exc:
                result = {
                    "run_id": f"unhandled_seed{seed:03d}",
                    "obstacle_id": obstacle["id"],
                    "experiment": args.experiment,
                    "seed": seed,
                    "valid": False,
                    "outcome": f"runner exception: {exc}",
                    "failure_class": "harness_failure",
                }
            results.append(result)
            print(
                f"{result['run_id']}: valid={result.get('valid')} "
                f"events={result.get('events', [])} outcome={result.get('outcome')}",
                flush=True,
            )
            if not args.dry_run:
                _write_manifest(args, obstacle, results)
    if args.dry_run:
        return 0
    return 0 if all(result.get("valid") for result in results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
