#!/usr/bin/env python3
"""Drive one leg of the course on the production stack, once per seed.

    scripts/run_segment.py --start 23 --end 24 --seeds 10 --out /res/post_wp16/fullstack

What this starts is the race: ``rl_deploy`` from the contest SDK, then
``segment.launch.py``, which includes ``race.launch.py`` unchanged. The follower runs with
its local planner, its step commit and its stall recovery; the lidar and height map are the
ones the perception node publishes; the joint commands come from the SDK's own policy runner
over its own DDS topic. The only test-only pieces are the spawn override the simulator reads
from the environment and the recorder that decides when the run is over.

This exists because the cheaper harness did not do that. ``training/s10_climb/segment_runner``
composes the ONNX policy, the course and pure pursuit, and nothing else -- no lidar, no local
planner, no step commit. It is fast and it is right about what it models, but a failure in it
is a failure of pure pursuit, not of the race. Three of its results were "drives into a wall"
on a stack with no obstacle avoidance in it at all.

Per seed it writes ``<out>/<start>_<end>_seed<N>.csv`` and ``.json``; ``--video`` adds a
frames directory. A final ``<out>/<start>_<end>.json`` collects the lot.

Run it inside the container, from the workspace root::

    CONTAINER_NAME=s10-seg docker/run.sh scripts/run_segment.py --start 23 --end 24
"""

from __future__ import annotations

import argparse
import json
import math
import os
import signal
import subprocess
import sys
import time
from pathlib import Path

import yaml

from runtime_fingerprint import check_fingerprint

REPO_ROOT = Path(__file__).resolve().parents[1]
COURSE = REPO_ROOT / "src/s10_bringup/config/course.yaml"
INSTALL = Path(os.environ.get("S10_INSTALL_BASE", REPO_ROOT / "install"))

#: Seconds to let ``rl_deploy`` build its ONNX session before physics starts stepping. Below
#: this the first commands arrive after the simulator has already dropped the robot.
POLICY_WARMUP = 2.0
#: Seconds to wait for the stack to come down before killing it outright. The simulator holds
#: a MuJoCo context and a passive viewer handle; not giving it a chance to release them leaves
#: the next run to discover it the hard way.
SHUTDOWN_GRACE = 8.0


def load_waypoints() -> list[dict]:
    data = yaml.safe_load(COURSE.read_text())
    return data["waypoints"]


def write_subcourse(waypoints: list[dict], start: int, end: int, path: Path) -> None:
    """Write waypoints ``start..end`` to their own file, keeping the real indices.

    A slice rather than a seek into the full course, so the follower cannot decide to drive
    back towards a waypoint behind the spawn. ``course.yaml`` itself is generated by
    ``scripts/extract_waypoints.py`` and is never touched: editing it would both break
    ``--check`` and silently change the scored run.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# Generated by scripts/run_segment.py for a test run. Not the scored course.\n"
        + yaml.safe_dump(
            {
                "metadata": {"source": str(COURSE), "segment": [start, end]},
                "waypoints": [
                    {"index": int(w["index"]), "position": [float(v) for v in w["position"]]}
                    for w in waypoints[start : end + 1]
                ],
            },
            sort_keys=False,
        )
    )


def spawn_environment(waypoints: list[dict], start: int, seed: int) -> dict[str, str]:
    """Environment telling the simulator where to start, which way to face, and on what.

    The waypoint's z goes out as well as its x and y, and it is not decoration. The course
    runs over itself -- waypoints 23 to 25 sit on a deck 1.19 m above open floor, 28 to 32 on
    one 3.27 m above it -- so a ground lookup that is only given (x, y) has several correct
    answers and picks the lowest. That is how a whole sweep of segment 23 to 24 was collected
    with the robot underneath the deck it was meant to be crossing.
    """
    here = waypoints[start]["position"]
    nxt = waypoints[min(start + 1, len(waypoints) - 1)]["position"]
    yaw = math.atan2(nxt[1] - here[1], nxt[0] - here[0])
    return {
        "S10_SPAWN_XY": f"{here[0]},{here[1]}",
        "S10_SPAWN_Z": f"{here[2]}",
        "S10_SPAWN_YAW": f"{yaw}",
        "S10_SPAWN_SEED": str(seed),
        "S10_SPAWN_INDEX": str(start),
    }


def run_once(args, waypoints: list[dict], seed: int, course_path: Path) -> dict:
    name = f"{args.start:02d}_{args.end:02d}{args.tag}_seed{seed}"
    out_dir = Path(args.out)
    env = dict(os.environ)
    env.update(spawn_environment(waypoints, args.start, seed))
    env["S10_USE_VIEWER"] = "0"
    env.setdefault("ROS_DOMAIN_ID", "1")
    if args.video:
        env["S10_SEGMENT_VIDEO"] = str(out_dir / f"{name}_frames")
        env["S10_SEGMENT_VIDEO_HZ"] = str(args.video_hz)

    log = (out_dir / f"{name}.log").open("w")
    policy = subprocess.Popen(
        ["ros2", "run", "s10_sdk_deploy", "rl_deploy"],
        env=env,
        stdout=log,
        stderr=log,
        start_new_session=True,
    )
    time.sleep(POLICY_WARMUP)
    command = [
        "ros2",
        "launch",
        "s10_bringup",
        "segment.launch.py",
        f"course_file:={course_path}",
        f"out_dir:={out_dir}",
        f"run_name:={name}",
        f"start_waypoint:={args.start}",
        f"end_waypoint:={args.end}",
        f"seed:={seed}",
        f"max_time:={args.max_time}",
        f"strategy_router:={'true' if args.router else 'false'}",
    ]
    if args.nav_params:
        command.append(f"nav_params:={args.nav_params}")
    if args.router_params:
        command.append(f"router_params:={args.router_params}")
    stack = subprocess.Popen(command, env=env, stdout=log, stderr=log, start_new_session=True)

    # The recorder ends the run; this is only the backstop for a stack that never got as far
    # as recording anything, which is a harness failure rather than a robot one.
    wall_budget = (
        args.wall_timeout
        if args.wall_timeout > 0.0
        else max(args.max_time * 10.0 + 300.0, args.max_time + 90.0)
    )
    deadline = time.monotonic() + wall_budget
    while stack.poll() is None and time.monotonic() < deadline:
        time.sleep(0.5)
    _terminate(stack)
    _terminate(policy)
    log.close()

    summary_path = out_dir / f"{name}.json"
    if summary_path.exists():
        return json.loads(summary_path.read_text())
    return {
        "start": args.start,
        "end": args.end,
        "seed": seed,
        "reached": False,
        "outcome": "the stack never produced a recording; see the log",
        "log": str(out_dir / f"{name}.log"),
    }


def _terminate(process: subprocess.Popen) -> None:
    if process.poll() is not None:
        return
    # ``ros2 run`` and ``ros2 launch`` are wrappers. Signalling only the wrapper leaves
    # rl_deploy and launch children orphaned on the shared DDS domain, where they continue
    # publishing actuator commands into the next seed. Each stack owns a process group so
    # teardown reaches the entire tree.
    os.killpg(process.pid, signal.SIGINT)
    try:
        process.wait(SHUTDOWN_GRACE)
    except subprocess.TimeoutExpired:
        os.killpg(process.pid, signal.SIGKILL)
        process.wait()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--start", type=int, required=True)
    parser.add_argument("--end", type=int, required=True)
    parser.add_argument("--seeds", type=int, default=3)
    parser.add_argument("--seed-from", type=int, default=0)
    parser.add_argument("--max-time", type=float, default=120.0)
    parser.add_argument(
        "--wall-timeout",
        type=float,
        default=0.0,
        help=(
            "host-time backstop per seed; 0 allows 10x real-time slowdown plus 300 s "
            "while max-time remains official simulation time"
        ),
    )
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--tag", default="", help="suffix, to keep an A/B pair apart")
    parser.add_argument("--nav-params", default="", help="override nav.yaml, for an A/B only")
    parser.add_argument(
        "--router-params", default="", help="override strategy.yaml when --router is enabled"
    )
    parser.add_argument("--router", action="store_true", help="insert the strategy router")
    parser.add_argument("--video", action="store_true")
    parser.add_argument("--video-hz", type=float, default=10.0)
    args = parser.parse_args(argv)
    args.tag = f"_{args.tag}" if args.tag else ""

    if not (INSTALL / "setup.bash").is_file():
        print(f"error: workspace not built at {INSTALL}; run scripts/build.sh", file=sys.stderr)
        return 2
    try:
        check_fingerprint(INSTALL)
    except (OSError, RuntimeError, ValueError, json.JSONDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    waypoints = load_waypoints()
    if not 0 <= args.start < args.end < len(waypoints):
        parser.error(f"need 0 <= start < end < {len(waypoints)}")

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    course_path = out_dir / f"course_{args.start:02d}_{args.end:02d}.yaml"
    write_subcourse(waypoints, args.start, args.end, course_path)

    results = []
    for seed in range(args.seed_from, args.seed_from + args.seeds):
        result = run_once(args, waypoints, seed, course_path)
        results.append(result)
        print(
            f"  {args.start:>2}->{args.end:<2} seed {seed}  "
            f"{'OK ' if result.get('reached') else 'FAIL'}  "
            f"{result.get('elapsed_s', 0.0):6.1f} s  {result.get('distance_m', 0.0):6.1f} m  "
            f"tilt {result.get('max_tilt_deg', 0.0):4.0f}  "
            f"stalls {result.get('stalls', 0)}  {result.get('outcome')}",
            flush=True,
        )

    summary = out_dir / f"{args.start:02d}_{args.end:02d}{args.tag}.json"
    summary.write_text(json.dumps(results, indent=2))
    passed = sum(1 for r in results if r.get("reached"))
    print(f"{passed}/{len(results)} reached waypoint {args.end}   -> {summary}")
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
