"""Drive one leg of the course headlessly, to find out which parts the robot can do.

The race is a single 33-waypoint run, which is the wrong shape for a question like "can the
robot get from waypoint 22 to waypoint 23". Answering that by running the whole race costs
several minutes and, worse, only tells you about the segment if everything before it went
right -- and the run currently stops dead at the 0.377 m step at waypoint 16, so nothing
after it has been observed at all.

This starts the robot at a chosen waypoint and drives to another one. It is deliberately the
real stack and not a model of it: the shipped ``policy.onnx``, the observation layout taken
from ``s10_rl.observation`` which is the same definition the C++ runner is generated from,
and the actual :class:`PurePursuitController` and :class:`Course` the follower node uses. A
failure here is a failure of the thing that will run in the race. A reimplementation would
only tell us about the reimplementation.

**This is test-only and off by default.** Nothing in the race launch imports it, it writes
only where it is told to, and it does not touch ``course.yaml`` -- a sub-course is built in
memory from a slice of the waypoint list, because hand-editing the generated course file
would both break ``extract_waypoints.py --check`` and silently change the scored run.

Usage::

    python3 -m s10_climb.segment_runner --start 22 --end 23 --seeds 3 --out /res/post_wp16

Seeds do not change the physics, which is deterministic. They jitter the starting pose --
position, heading and joint angles -- because the question worth answering is not "does this
work from one exact pose" but "does this work". A segment that only succeeds from a single
spawn is a segment that will fail in a real run, where the robot arrives however it arrives.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import struct
import sys
import zlib
from dataclasses import asdict, dataclass, field
from pathlib import Path

import mujoco
import numpy as np
import onnxruntime as ort
from s10_climb.sandbox import JOINT_INIT, POLICY_KD, POLICY_KP, Sandbox, find_track_xml

from s10_auto_nav.pure_pursuit import PurePursuitController, PursuitGains
from s10_auto_nav.waypoints import Course, Waypoint
from s10_rl.observation import (
    ACTION_SCALE,
    DEFAULT_JOINT_POS,
    DOF_VEL_SCALE,
    OMEGA_SCALE,
    POLICY_ORDER,
    ROBOT_ORDER,
)

#: The policy shipped with the SDK, relative to the repository root.
POLICY_PATH = Path(
    "upstream/goai_embodied_future_material/src/S10_sdk_deploy/policy/policy.onnx"
)
#: Waypoints, as generated by scripts/extract_waypoints.py.
COURSE_PATH = Path("src/s10_bringup/config/course.yaml")

#: The policy runs at 50 Hz against a 1 ms simulation, matching ``SetDecimation(4)`` on the
#: SDK's 200 Hz control loop. The follower node publishes at the same rate.
POLICY_EVERY = 20
CONTROL_DT = 0.02

#: Terrain only. Group 1 is the robot and group 2 is the decorative route overlay, which has
#: collision disabled. Excluding both matters twice over: the overlay floats above the ground
#: and would be reported as terrain, and the robot would otherwise block the rays cast to
#: find the ground beneath it -- the height check would then measure the top of its own base.
GEOMGROUP = np.array([1, 0, 0, 0, 0, 0], dtype=np.uint8)

#: Index permutations between the two joint orderings, derived from the names rather than
#: written out, so they cannot drift from ``s10_rl.observation``.
ROBOT2POLICY = np.array([ROBOT_ORDER.index(n) for n in POLICY_ORDER])
POLICY2ROBOT = np.array([POLICY_ORDER.index(n) for n in ROBOT_ORDER])

DEFAULT_POLICY = np.asarray(DEFAULT_JOINT_POS, dtype=np.float64)
DEFAULT_ROBOT = DEFAULT_POLICY[POLICY2ROBOT]
SCALE_ROBOT = np.asarray(ACTION_SCALE, dtype=np.float64)

#: Past this the robot is on its way over and will not recover; ending the episode saves the
#: several seconds it would spend sliding.
FALL_TILT_DEG = 70.0
#: How far below the terrain the base may sink before the run is called a fall. Generous: the
#: robot legitimately drops off ledges.
FALL_BELOW_M = 1.2


def ground_height(model, data, x: float, y: float, z_ref: float) -> float:
    """Height of the surface at (x, y) that a robot near ``z_ref`` would be standing on.

    Casting down from high above finds the roof rather than the floor wherever the course
    runs over itself, and the surfaces cannot be told apart by the order the rays return
    them in -- the scene is meshes, and a ray crosses a non-convex mesh any number of times.
    So a candidate is tested: fire again from just above it, and if the ray comes back to the
    same surface then that space is empty and the robot could stand there.
    """
    z = 14.0
    down = np.array([0.0, 0.0, -1.0])
    gid = np.zeros(1, dtype=np.int32)
    best = float("nan")
    for _ in range(24):
        dist = mujoco.mj_ray(model, data, np.array([x, y, z]), down, GEOMGROUP, 1, -1, gid)
        if dist < 0:
            break
        hit = z - dist
        back = mujoco.mj_ray(
            model, data, np.array([x, y, hit + 0.25]), down, GEOMGROUP, 1, -1, gid
        )
        if back >= 0 and abs(back - 0.25) < 1e-6:
            best = hit
            if hit <= z_ref + 0.9:
                return hit
        nxt = hit - 0.005
        if nxt >= z - 1e-9:
            break
        z = nxt
    return best


class Policy:
    """The shipped ONNX policy, driven exactly as ``s10_policy_runner.hpp`` drives it.

    The observation assembly is copied term by term from that header rather than from the
    training code, because the header is what will run. The two are supposed to agree, and
    checking that they do is not this file's job.
    """

    def __init__(self, path: Path, model):
        self.session = ort.InferenceSession(str(path), providers=["CPUExecutionProvider"])
        self.last_action = np.zeros(16)
        # Read the same sensors the deployed stack reads. ``qvel[3:6]`` is the same quantity
        # for a free joint, but going through the sensors means the observation comes from
        # where the race gets it, and any disagreement about which frame or which site is
        # involved resolves the same way here as it will there.
        self.gyro = self._sensor_adr(model, mujoco.mjtSensor.mjSENS_GYRO)
        self.quat = self._sensor_adr(model, mujoco.mjtSensor.mjSENS_FRAMEQUAT)

    @staticmethod
    def _sensor_adr(model, kind) -> int:
        for i in range(model.nsensor):
            if model.sensor_type[i] == kind:
                return int(model.sensor_adr[i])
        raise ValueError(f"the scene has no {kind!r} sensor")

    def reset(self) -> None:
        self.last_action = np.zeros(16)

    def observe(self, sb: Sandbox, command) -> np.ndarray:
        omega = sb.data.sensordata[self.gyro : self.gyro + 3] * OMEGA_SCALE
        rot = np.zeros(9)
        mujoco.mju_quat2Mat(rot, sb.data.sensordata[self.quat : self.quat + 4])
        # Gravity expressed in the body frame. R maps body to world, so its third row is the
        # world vertical seen from the body, and gravity is the negative of that.
        projected_gravity = -rot.reshape(3, 3)[2, :]
        joint_pos = sb.q[ROBOT2POLICY].copy()
        joint_vel = sb.dq[ROBOT2POLICY] * DOF_VEL_SCALE
        # Wheels spin without limit, so their absolute angle carries no information and the
        # runner zeroes it. Leaving it in would feed the network an ever-growing number.
        joint_pos[12:16] = 0.0
        joint_pos -= DEFAULT_POLICY
        return np.concatenate(
            [omega, projected_gravity, np.asarray(command, float), joint_pos, joint_vel,
             self.last_action]
        ).astype(np.float32)

    def act(self, obs: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        """Return ``(pos_cmd, vel_cmd)`` in robot order, ready for the sandbox."""
        out = self.session.run(["actions"], {"obs": obs[None, :]})[0]
        action = np.asarray(out, dtype=np.float64).reshape(16)
        self.last_action = action
        target = action[POLICY2ROBOT] * SCALE_ROBOT + DEFAULT_ROBOT

        pos_cmd = np.zeros(16)
        vel_cmd = np.zeros(16)
        for leg in range(4):
            pos_cmd[leg * 4 : leg * 4 + 3] = target[leg * 4 : leg * 4 + 3]
            # The wheel channel is a velocity. Its kp is zero, so writing it as a position
            # target would command nothing at all rather than fail.
            vel_cmd[leg * 4 + 3] = target[leg * 4 + 3]
        return pos_cmd, vel_cmd


@dataclass
class RunResult:
    start: int
    end: int
    seed: int
    reached: bool = False
    outcome: str = "unknown"
    waypoints_cleared: int = 0
    elapsed_s: float = 0.0
    distance_m: float = 0.0
    remaining_m: float = 0.0
    max_tilt_deg: float = 0.0
    final_xyz: tuple = (0.0, 0.0, 0.0)
    saturated_joints: int = 0
    spawn_xyz: tuple = (0.0, 0.0, 0.0)
    spawn_yaw_deg: float = 0.0
    settle_ok: bool = True
    settle_note: str = ""
    csv: str = ""
    frames: str = ""
    profile: list = field(default_factory=list)


def _yaw_towards(frm: np.ndarray, to: np.ndarray) -> float:
    delta = np.asarray(to)[:2] - np.asarray(frm)[:2]
    return float(math.atan2(delta[1], delta[0]))


def _write_png(path: Path, rgb: np.ndarray) -> None:
    """Write an RGB array as a PNG, with no image library.

    The container has no imageio, no PIL, no OpenCV and no ffmpeg, and adding one to the
    production dependencies to save debug frames would be the wrong trade. PNG's stored
    format is simple enough to emit directly: a filter byte per row, zlib over the lot.
    """
    height, width, _ = rgb.shape
    raw = b"".join(b"\x00" + rgb[y].tobytes() for y in range(height))

    def chunk(tag: bytes, payload: bytes) -> bytes:
        body = tag + payload
        return struct.pack(">I", len(payload)) + body + struct.pack(">I", zlib.crc32(body))

    header = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    path.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", header)
        + chunk(b"IDAT", zlib.compress(raw, 6))
        + chunk(b"IEND", b"")
    )


def run_segment(
    sb: Sandbox,
    policy: Policy,
    waypoints: list[Waypoint],
    start: int,
    end: int,
    seed: int,
    *,
    max_time: float = 60.0,
    settle: float = 1.0,
    spawn_z: float = 0.2,
    out_dir: Path | None = None,
    video: bool = False,
    video_hz: float = 10.0,
    brake_distance: float | None = None,
    tag: str = "",
) -> RunResult:
    """Spawn at ``start``, follow the course to ``end``, and report what happened."""
    result = RunResult(start=start, end=end, seed=seed)
    rng = np.random.default_rng(seed)
    # Static geometry is placed by the first forward pass. Ray casting before it reports
    # every terrain geom sitting at the origin, which shows up as "no ground anywhere".
    mujoco.mj_forward(sb.model, sb.data)

    here = waypoints[start].position
    nxt = waypoints[start + 1].position if start + 1 < len(waypoints) else here
    # Jitter is small on purpose: it should represent arriving at the waypoint slightly
    # differently, not being dropped somewhere else.
    offset = rng.normal(0.0, 0.05, 2) if seed else np.zeros(2)
    yaw = _yaw_towards(here, nxt) + (math.radians(rng.normal(0.0, 4.0)) if seed else 0.0)
    joints = JOINT_INIT + (rng.normal(0.0, 0.01, 16) if seed else 0.0)

    x, y = float(here[0]) + offset[0], float(here[1]) + offset[1]
    floor = ground_height(sb.model, sb.data, x, y, float(here[2]))
    if not np.isfinite(floor):
        result.outcome = "no ground under the start waypoint"
        result.settle_ok = False
        return result

    sb.reset((x, y, floor + spawn_z), joints=joints)
    half = yaw / 2.0
    sb.data.qpos[3:7] = (math.cos(half), 0.0, 0.0, math.sin(half))
    mujoco.mj_forward(sb.model, sb.data)
    result.spawn_xyz = (round(x, 3), round(y, 3), round(floor + spawn_z, 3))
    result.spawn_yaw_deg = round(math.degrees(yaw), 1)

    # The race does not drop the robot into a standing pose, and neither does this. It spawns
    # crouched at JOINT_INIT 0.2 m up, exactly as `mujoco_simulation_ros2.py` does with
    # TRACK_START_BASE_POS, and the SDK's state machine stands it up before the policy takes
    # over. Skipping the stand-up and starting from a stance instead was tried first and was
    # worse than wrong: from some heights the robot bounced and flipped onto its back, which
    # reads as a segment the robot cannot do rather than a spawn it was never given.
    for _ in range(int(0.3 / sb.model.opt.timestep)):
        sb.step(joints, kp=POLICY_KP, kd=POLICY_KD)
    rise = int(settle / sb.model.opt.timestep)
    for i in range(rise):
        blend = (i + 1) / rise
        sb.step(joints * (1.0 - blend) + DEFAULT_ROBOT * blend, kp=POLICY_KP, kd=POLICY_KD)
    for _ in range(int(0.3 / sb.model.opt.timestep)):
        sb.step(DEFAULT_ROBOT, kp=POLICY_KP, kd=POLICY_KD)

    # Checked rather than assumed: a spawn that ends up inside geometry or bouncing produces
    # a plausible-looking failed run, and the failure belongs to the harness, not the robot.
    # A good stand-up lands at 0.40 m with under a degree of tilt on level ground.
    contacts = sum(1 for c in sb.data.contact[: sb.data.ncon] if c.dist < 0.002)
    settled_height = float(sb.base_pos[2]) - floor
    if sb.tilt_deg() > 25.0:
        result.settle_ok = False
        result.settle_note = f"tilted {sb.tilt_deg():.1f} deg after settling"
    elif contacts < 3:
        result.settle_ok = False
        result.settle_note = f"only {contacts} contacts after settling"
    elif not 0.25 < settled_height < 0.60:
        result.settle_ok = False
        result.settle_note = f"base {settled_height:.3f} m above ground after settling"
    if not result.settle_ok:
        result.outcome = f"bad spawn: {result.settle_note}"
        result.final_xyz = tuple(round(v, 3) for v in sb.base_pos)
        return result

    # A sub-course rather than a seek into the full one, so the follower cannot wander back
    # towards waypoints behind the start.
    course = Course([waypoints[i] for i in range(start, end + 1)])
    controller = PurePursuitController(PursuitGains(brake_distance=brake_distance))
    policy.reset()

    rows: list[dict] = []
    frames_dir = None
    renderer = None
    if video and out_dir is not None:
        frames_dir = out_dir / f"seg{start:02d}_{end:02d}{tag}_seed{seed}_frames"
        frames_dir.mkdir(parents=True, exist_ok=True)
        renderer = mujoco.Renderer(sb.model, height=480, width=640)
        result.frames = str(frames_dir)

    camera = mujoco.MjvCamera()
    camera.distance, camera.elevation, camera.azimuth = 4.0, -20.0, 90.0

    travelled = 0.0
    last_xy = sb.base_pos[:2].copy()
    pos_cmd, vel_cmd = JOINT_INIT.copy(), np.zeros(16)
    command = (0.0, 0.0, 0.0)
    steps = int(max_time / sb.model.opt.timestep)
    next_frame = 0.0
    frame_no = 0

    for i in range(steps):
        t = i * sb.model.opt.timestep
        if i % POLICY_EVERY == 0:
            pos = sb.base_pos
            rot = sb.data.xmat[sb.base].reshape(3, 3)
            heading = math.atan2(rot[1, 0], rot[0, 0])
            course.update(pos[:2])
            if course.finished:
                result.reached = True
                result.outcome = "reached the end waypoint"
                break
            target = course.lookahead_point(pos[:2], controller.lookahead_distance())
            command = controller.compute(pos[:2], heading, target, CONTROL_DT).as_tuple()
            pos_cmd, vel_cmd = policy.act(policy.observe(sb, command))

            travelled += float(np.linalg.norm(pos[:2] - last_xy))
            last_xy = pos[:2].copy()
            result.max_tilt_deg = max(result.max_tilt_deg, sb.tilt_deg())
            rows.append(
                {
                    "t": round(t, 3),
                    "x": round(float(pos[0]), 4),
                    "y": round(float(pos[1]), 4),
                    "z": round(float(pos[2]), 4),
                    "yaw_deg": round(math.degrees(heading), 2),
                    "tilt_deg": round(sb.tilt_deg(), 2),
                    "cmd_forward": round(command[0], 3),
                    "cmd_lateral": round(command[1], 3),
                    "cmd_yaw": round(command[2], 3),
                    "cursor": int(course.cursor),
                    "waypoint": int(course.waypoints[course.cursor].index),
                }
            )

            floor_now = ground_height(sb.model, sb.data, float(pos[0]), float(pos[1]),
                                      float(pos[2]))
            if sb.tilt_deg() > FALL_TILT_DEG:
                result.outcome = f"fell over (tilt {sb.tilt_deg():.0f} deg)"
                break
            if np.isfinite(floor_now) and pos[2] < floor_now - FALL_BELOW_M:
                result.outcome = "fell off the course"
                break

        if renderer is not None and t >= next_frame:
            camera.lookat[:] = sb.base_pos
            renderer.update_scene(sb.data, camera)
            _write_png(frames_dir / f"{frame_no:05d}.png", renderer.render())
            frame_no += 1
            next_frame = t + 1.0 / video_hz

        sb.step(pos_cmd, vel_cmd=vel_cmd, kp=POLICY_KP, kd=POLICY_KD)

    else:
        result.outcome = f"ran out of time after {max_time:.0f} s"

    if renderer is not None:
        renderer.close()

    pos = sb.base_pos
    course.update(pos[:2])
    result.elapsed_s = round(rows[-1]["t"] if rows else 0.0, 2)
    result.distance_m = round(travelled, 2)
    # The sub-course's first waypoint is where the robot spawned, so the cursor counts it
    # as reached before the run starts. What matters is how many *targets* were met.
    result.waypoints_cleared = max(0, min(int(course.cursor) - 1, end - start))
    result.remaining_m = round(float(course.remaining_distance(pos[:2])), 2)
    result.max_tilt_deg = round(result.max_tilt_deg, 1)
    result.final_xyz = tuple(round(float(v), 3) for v in pos)
    result.saturated_joints = int(sb.saturated.sum())
    result.profile = [[r["t"], r["z"]] for r in rows[:: max(1, len(rows) // 60)]]

    if out_dir is not None and rows:
        out_dir.mkdir(parents=True, exist_ok=True)
        path = out_dir / f"seg{start:02d}_{end:02d}{tag}_seed{seed}.csv"
        with path.open("w", newline="") as handle:
            writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
            writer.writeheader()
            writer.writerows(rows)
        result.csv = str(path)
    return result


def repo_root() -> Path:
    return find_track_xml().parents[7]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--start", type=int, required=True, help="waypoint to spawn at")
    parser.add_argument("--end", type=int, required=True, help="waypoint to drive to")
    parser.add_argument("--seeds", type=int, default=3, help="how many spawn variations")
    parser.add_argument("--seed-from", type=int, default=0)
    parser.add_argument("--max-time", type=float, default=60.0)
    parser.add_argument("--spawn-z", type=float, default=0.2,
                        help="crouched spawn height above the ground")
    parser.add_argument("--settle", type=float, default=1.0,
                        help="seconds spent standing up before driving")
    parser.add_argument("--out", type=Path, default=None, help="where CSV and JSON go")
    parser.add_argument("--video", action="store_true", help="write PNG frames (slow)")
    parser.add_argument("--brake-distance", type=float, default=None,
                        help="override PursuitGains.brake_distance; unset races as shipped")
    parser.add_argument("--tag", default="", help="suffix for output files, to keep A/B runs apart")
    args = parser.parse_args(argv)

    root = repo_root()
    waypoints = Course.from_yaml(root / COURSE_PATH).waypoints
    if not 0 <= args.start < args.end < len(waypoints):
        parser.error(f"need 0 <= start < end < {len(waypoints)}")

    # A tag keeps an A/B pair from overwriting each other's CSVs.
    tag = f"_{args.tag}" if args.tag else ""

    sb = Sandbox()
    policy = Policy(root / POLICY_PATH, sb.model)

    results = []
    for seed in range(args.seed_from, args.seed_from + args.seeds):
        r = run_segment(
            sb, policy, waypoints, args.start, args.end, seed,
            max_time=args.max_time, settle=args.settle, spawn_z=args.spawn_z,
            out_dir=args.out, video=args.video, brake_distance=args.brake_distance,
            tag=tag,
        )
        results.append(r)
        print(
            f"  {args.start:>2}->{args.end:<2} seed {seed}  "
            f"{'OK ' if r.reached else 'FAIL'}  "
            f"cleared {r.waypoints_cleared}/{args.end - args.start}  "
            f"{r.elapsed_s:5.1f} s  {r.distance_m:5.1f} m  "
            f"tilt {r.max_tilt_deg:4.0f}  {r.outcome}",
            flush=True,
        )

    if args.out is not None:
        args.out.mkdir(parents=True, exist_ok=True)
        path = args.out / f"seg{args.start:02d}_{args.end:02d}{tag}.json"
        path.write_text(json.dumps([asdict(r) for r in results], indent=2))
        print(f"wrote {path}")

    passed = sum(1 for r in results if r.reached)
    print(f"{passed}/{len(results)} reached waypoint {args.end}")
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
